language: php
php:
  - 7.1
  
   
before_script:
  - composer install --dev
  - mysql -e 'CREATE DATABASE dbal_gateway;'
  - mysql dbal_gateway < sql/database.sql 
  
  
script: phpunit --configuration travis.xml
